blueprint:
  name: Auto Steer Thermostat Temperature
  description: Set the target temperature on thermostat depending on multiple properties
  domain: automation
  author: Krzysztof Czaja

  # UI Inputs
  input:
    # Thermostat input
    thermostat:
      name: Termostat
      description: Jakim termostatem zarządzać
      selector:
        entity:
          filter:
            - domain: climate

    # Window sensors input
    window_sensors:
      name: Czujniki otwarcia okna
      description: Będą wykorzystane do wyłączania ogrzewania, gdy okno jest otwarte.
      selector:
        entity:
          filter:
            - domain: binary_sensor
          multiple: true

    # Winter mode input
    winter_mode:
      name: Tryb zimowy
      description: Jeśli wyłączony to automatyzacja nie będzie działać
      selector:
        entity:
          filter:
            - domain: input_boolean

    # Away mode input
    away_mode:
      name: Tryb poza domem
      description: Jeśli włączony to termostaty będą ustawione na minimalne grzanie
      selector:
        entity:
          filter:
            - domain: input_boolean

    # Heating schedule input 
    schedule:
      name: Harmonogram pracy
      description: Zależnie od niego będzie ustawiona temperature dzienna, bądź nocna
      selector:
        entity:
          filter:
            - domain: schedule

    # Day temperature input
    temperature_day:
      name: Temperatura dzienna
      description: Temperatura jaka powinna być ustawiona w dzień
      selector:
        entity:
          filter:
            - domain: input_number

    # Night temperature input
    temperature_night:
      name: Temperatura nocna
      description: Temperatura jaka powinna być ustawiona w nocy
      selector:
        entity:
          filter:
            - domain: input_number
    
    # Away temperature input
    temperature_away:
      name: Temperatura minimalna
      description: Temperatura jaka powinna być ustawiona, gdy tryb poza domem jest włączony
      selector:
        entity:
          filter:
            - domain: input_number
            
trigger:
  - platform: state
    entity_id:
      - !input schedule
      - !input winter_mode
      - !input away_mode
      - !input temperature_day
      - !input temperature_night
      - !input temperature_away
      
  - platform: state
    entity_id: !input window_sensors
      
condition:
  - condition: state
    entity_id: !input winter_mode
    state: "on"
    
action:
  - variables:
      temperature_day_input: !input temperature_day
      temperature_night_input: !input temperature_night
      temperature_away_input: !input temperature_away
  
  - choose:
    - conditions:
      - condition: state
        entity_id: !input window_sensors
        state: "on"
        match: any
        alias: Okno otwarte
      sequence:
        - service: climate.set_hvac_mode
          data:
            hvac_mode: off
          target:
            entity_id: !input thermostat
        
    - conditions:
      - condition: state
        entity_id: !input away_mode
        state: "on"
        alias: Tryb poza domem włączony 
      sequence:
        - service: climate.set_hvac_mode
          data:
            hvac_mode: heat
          target:
            entity_id: !input thermostat
        - service: climate.set_temperature
          data:
            temperature: "{{ states(temperature_away_input) }}"
          target:
            entity_id: !input thermostat

    - conditions:
      - condition: state
        entity_id: !input schedule
        state: "on"
        alias: Jest dzień
      sequence:
        - service: climate.set_hvac_mode
          data:
            hvac_mode: heat
          target:
            entity_id: !input thermostat
        - service: climate.set_temperature
          data:
            temperature: "{{ states(temperature_day_input) }}"
          target:
            entity_id: !input thermostat
          alias: Ustaw dzienną temperaturę

    default:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        target:
          entity_id: !input thermostat
      - service: climate.set_temperature
        data:
          temperature: "{{ states(temperature_night_input) }}"
        target:
          entity_id: !input thermostat
        alias: Ustaw nocną temperaturę
mode: single
