blueprint:
  name: Auto Steer Thermostat Temperature
  description: Set the target temperature on thermostat depending on multiple properties
  domain: automation
  author: Krzysztof Czaja
  input:
    thermostat:
      name: Termostat
      description: Jakim termostatem zarządzać
      selector:
        entity:
          filter:
            - domain: climate
    winter_mode:
      name: Tryb zimowy
      description: Jeśli wyłączony to automatyzacja nie będzie działać
      selector:
        entity:
          filter:
            - domain: input_boolean
    away_mode:
      name: Tryb poza domem
      description: Jeśli włączony to termostaty będą ustawione na minimalne grzanie
      selector:
        entity:
          filter:
            - domain: input_boolean
    schedule:
      name: Harmonogram pracy
      description: Zależnie od niego będzie ustawiona temperature dzienna, bądź nocna
      selector:
        entity:
          filter:
            - domain: schedule
    temperature_day:
      name: Temperatura dzienna
      description: Temperatura jaka powinna być ustawiona w dzień
      selector:
        entity:
          filter:
            - domain: input_number
    temperature_night:
      name: Temperatura nocna
      description: Temperatura jaka powinna być ustawiona w nocy
      selector:
        entity:
          filter:
            - domain: input_number
    temperature_away:
      name: Temperatura minimalna
      description: Temperatura jaka powinna być ustawiona, gdy tryb poza domem jest włączony
      selector:
        entity:
          filter:
            - domain: input_number
trigger:
  - platform: state
    entity_id:
      - !input schedule
      - !input winter_mode
      - !input away_mode
      - !input temperature_day
      - !input temperature_night
      - !input temperature_away
condition:
  - condition: state
    entity_id: !input winter_mode
    state: "on"
action:
  - variables:
      thermostat_input: !input thermostat
      temperature_day_input: !input temperature_day
      temperature_night_input: !input temperature_night
      temperature_away_input: !input temperature_away
  - if:
      - condition: state
        entity_id: !input away_mode
        state: "off"
        alias: Poza domem
    then:
      - if:
          - condition: state
            entity_id: !input schedule
            state: "on"
            alias: Jest dzień
        then:
          - service: climate.set_temperature
            metadata: {}
            data:
              temperature: "{{ states(temperature_day_input) }}"
            target:
              entity_id: "{{ thermostat_input }}"
            alias: Ustaw dzienną temperaturę
        else:
          - service: climate.set_temperature
            metadata: {}
            data:
              temperature: "{{ states(temperature_night_input) }}"
            target:
              entity_id: "{{ thermostat_input }}"
            alias: Ustaw nocną temperaturę
        alias: Ustaw ogrzewanie dzień/noc
    else:
      - service: climate.set_temperature
        metadata: {}
        data:
          temperature: "{{ states(temperature_away_input) }}"
        target:
          entity_id: "{{ thermostat_input }}"
        alias: Ustaw minimalną temperaturę
    alias: Steruj termostatem
mode: single
