blueprint:
  name: Steer light with IKEA remote
  description: Use IKEA remote to turn on/off light and increase/decrease brightness.
  domain: automation
  author: Krzysztof Czaja
  
  input:
    light:
      name: Oświetlenie
      description: Oświetlenie, które będzie sterowane pilotem
      selector:
        target:
        
    remote:
      name: Włącznik światła
      description: Włacznik światła IKEA, którym chcemy zarządzać wybranym oświetleniem
      selector:
        device:
          entity:
            integration: mqtt

trigger:
  - trigger: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: "on"
    # discovery_id: 0xf082c0fffe0d976f action_on
    id: Włącznik naciśnięty
    
  - trigger: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: "off"
    # discovery_id: 0xf082c0fffe0d976f action_off
    id: Wyłącznik naciśnięty
    
  - trigger: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: brightness_move_up
    # discovery_id: 0xf082c0fffe0d976f action_brightness_move_up
    id: Włącznik przytrzymany
    
  - trigger: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: brightness_move_down
    # discovery_id: 0xf082c0fffe0d976f action_brightness_move_down
    id: Wyłącznik przytrzymany

    -  trigger: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: brightness_stop
    id: Przerwanie akcji
    
condition: []

action:
    choose:
      - conditions:
          - condition: trigger
            id:
              - Włącznik naciśnięty
        sequence:
          - alias: Włącz światło
            service: light.turn_on
            data: {}
            target: !input light
        
      - conditions:
          - condition: trigger
            id:
              - Wyłącznik naciśnięty
        sequence:
          - alias: Wyłącz światło
            service: light.turn_off
            data: {}
            target: !input light
        
      - conditions:
          - condition: trigger
            id:
              - Włącznik przytrzymany
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: 5
                    transition: 0.2
                  target: !input light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
              
      - conditions:
        - condition: trigger
          id:
            - Wyłącznik przytrzymany
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  data:
                    transition: 0.2
                    brightness_step_pct: -5
                  target: !input light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
mode: single
